admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

application:
    resource: "@ApplicationBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"