<?php

namespace AdminBundle\Repository;

/**
 * AdherantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdherantRepository extends \Doctrine\ORM\EntityRepository
{
	//recupérer la liste des adhérants et les classée par ordre décroissant
	public function findAllAdherant()
	{
	  $qb = $this->createQueryBuilder('a');
	  $qb->orderBy('a.id', 'DESC');

	  return $qb
		->getQuery()
		->getResult()
	  ;
	}
}
