<?php

namespace AdminBundle\Repository;

/**
 * AppeloffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppeloffreRepository extends \Doctrine\ORM\EntityRepository
{
	//recupérer toutes les réunions et les classée par ordre décroissant
	public function findAllAppelOffre()
	{
	  $qb = $this->createQueryBuilder('a');
	  $qb->orderBy('a.id', 'DESC');

	  return $qb
		->getQuery()
		->getResult()
	  ;
	}
}
