<?php

namespace AdminBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	
	//recupérer touts les articles et les classée par ordre décroissant
	public function findAllArticle()
	{
	  $qb = $this->createQueryBuilder('a');
	  $qb->orderBy('a.id', 'DESC');

	  return $qb
		->getQuery()
		->getResult()
	  ;
	}
}
