<?php

namespace AdminBundle\Repository;

/**
 * PartenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenaireRepository extends \Doctrine\ORM\EntityRepository
{
	//Récupérer la liste des partenaire administrationet institutionnels
   public function findListePartenaireAdministrations()
   {
		$qb = $this->createQueryBuilder('p');
		$qb->where('p.types = :type')
			->setParameter('type', 'Administrations');
			return $qb->getQuery()
					  ->getResult();
   }
   //liste des partenaires entreprise/startup
   public function findListePartenaireEntreprise()
   {
		$qb = $this->createQueryBuilder('p');
		$qb->where('p.types = :type')
			->setParameter('type', 'Entreprise');
			return $qb->getQuery()
					  ->getResult();
   }
   
    //liste des partenaires associations
   public function findListePartenaireAssociation()
   {
		$qb = $this->createQueryBuilder('p');
		$qb->where('p.types = :type')
			->setParameter('type', 'Association');
			return $qb->getQuery()
					  ->getResult();
   }
}
