<?php

namespace AdminBundle\Repository;

/**
 * ReunionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReunionRepository extends \Doctrine\ORM\EntityRepository
{
	//recupérer toutes les réunions et les classée par ordre décroissant
	public function findAllReunion()
	{
	  $qb = $this->createQueryBuilder('r');
	  $qb->orderBy('r.id', 'DESC');

	  return $qb
		->getQuery()
		->getResult()
	  ;
	}
}
