<?php

namespace AdminBundle\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
	
	//recupérer touts les articles et les classée par ordre décroissant
	public function findAllVideo()
	{
	  $qb = $this->createQueryBuilder('v');
	  $qb->orderBy('v.id', 'DESC');

	  return $qb
		->getQuery()
		->getResult()
	  ;
	}
}
